-- Wipe all data while keeping schema intact
-- This truncates all tables and resets auto-increment counters

-- Disable foreign key constraints temporarily
ALTER TABLE "Feedback" DISABLE TRIGGER ALL;
ALTER TABLE "PromoRedemption" DISABLE TRIGGER ALL;
ALTER TABLE "ReferralEvent" DISABLE TRIGGER ALL;
ALTER TABLE "ReferralCode" DISABLE TRIGGER ALL;
ALTER TABLE "UserBadge" DISABLE TRIGGER ALL;
ALTER TABLE "ScanStreak" DISABLE TRIGGER ALL;
ALTER TABLE "BitesLedger" DISABLE TRIGGER ALL;
ALTER TABLE "BitesBalance" DISABLE TRIGGER ALL;
ALTER TABLE "PantryItem" DISABLE TRIGGER ALL;
ALTER TABLE "PurchaseHistory" DISABLE TRIGGER ALL;
ALTER TABLE "PriceObservation" DISABLE TRIGGER ALL;
ALTER TABLE "PriceAlert" DISABLE TRIGGER ALL;
ALTER TABLE "CanonicalPrice" DISABLE TRIGGER ALL;
ALTER TABLE "PriceSnapshot" DISABLE TRIGGER ALL;
ALTER TABLE "Meal" DISABLE TRIGGER ALL;
ALTER TABLE "Recipe" DISABLE TRIGGER ALL;
ALTER TABLE "MealPlan" DISABLE TRIGGER ALL;
ALTER TABLE "Collection" DISABLE TRIGGER ALL;
ALTER TABLE "Favourite" DISABLE TRIGGER ALL;
ALTER TABLE "PurchaseReminder" DISABLE TRIGGER ALL;
ALTER TABLE "Announcement" DISABLE TRIGGER ALL;
ALTER TABLE "FamilyProfile" DISABLE TRIGGER ALL;
ALTER TABLE "UserProfile" DISABLE TRIGGER ALL;
ALTER TABLE "User" DISABLE TRIGGER ALL;

-- Truncate all tables (CASCADE handles foreign keys)
TRUNCATE TABLE "Feedback" CASCADE;
TRUNCATE TABLE "PromoRedemption" CASCADE;
TRUNCATE TABLE "ReferralEvent" CASCADE;
TRUNCATE TABLE "ReferralCode" CASCADE;
TRUNCATE TABLE "UserBadge" CASCADE;
TRUNCATE TABLE "ScanStreak" CASCADE;
TRUNCATE TABLE "BitesLedger" CASCADE;
TRUNCATE TABLE "BitesBalance" CASCADE;
TRUNCATE TABLE "PantryItem" CASCADE;
TRUNCATE TABLE "PurchaseHistory" CASCADE;
TRUNCATE TABLE "PriceObservation" CASCADE;
TRUNCATE TABLE "PriceAlert" CASCADE;
TRUNCATE TABLE "CanonicalPrice" CASCADE;
TRUNCATE TABLE "PriceSnapshot" CASCADE;
TRUNCATE TABLE "Meal" CASCADE;
TRUNCATE TABLE "Recipe" CASCADE;
TRUNCATE TABLE "MealPlan" CASCADE;
TRUNCATE TABLE "Collection" CASCADE;
TRUNCATE TABLE "Favourite" CASCADE;
TRUNCATE TABLE "PurchaseReminder" CASCADE;
TRUNCATE TABLE "Announcement" CASCADE;
TRUNCATE TABLE "FamilyProfile" CASCADE;
TRUNCATE TABLE "UserProfile" CASCADE;
TRUNCATE TABLE "User" CASCADE;

-- Re-enable triggers
ALTER TABLE "Feedback" ENABLE TRIGGER ALL;
ALTER TABLE "PromoRedemption" ENABLE TRIGGER ALL;
ALTER TABLE "ReferralEvent" ENABLE TRIGGER ALL;
ALTER TABLE "ReferralCode" ENABLE TRIGGER ALL;
ALTER TABLE "UserBadge" ENABLE TRIGGER ALL;
ALTER TABLE "ScanStreak" ENABLE TRIGGER ALL;
ALTER TABLE "BitesLedger" ENABLE TRIGGER ALL;
ALTER TABLE "BitesBalance" ENABLE TRIGGER ALL;
ALTER TABLE "PantryItem" ENABLE TRIGGER ALL;
ALTER TABLE "PurchaseHistory" ENABLE TRIGGER ALL;
ALTER TABLE "PriceObservation" ENABLE TRIGGER ALL;
ALTER TABLE "PriceAlert" ENABLE TRIGGER ALL;
ALTER TABLE "CanonicalPrice" ENABLE TRIGGER ALL;
ALTER TABLE "PriceSnapshot" ENABLE TRIGGER ALL;
ALTER TABLE "Meal" ENABLE TRIGGER ALL;
ALTER TABLE "Recipe" ENABLE TRIGGER ALL;
ALTER TABLE "MealPlan" ENABLE TRIGGER ALL;
ALTER TABLE "Collection" ENABLE TRIGGER ALL;
ALTER TABLE "Favourite" ENABLE TRIGGER ALL;
ALTER TABLE "PurchaseReminder" ENABLE TRIGGER ALL;
ALTER TABLE "Announcement" ENABLE TRIGGER ALL;
ALTER TABLE "FamilyProfile" ENABLE TRIGGER ALL;
ALTER TABLE "UserProfile" ENABLE TRIGGER ALL;
ALTER TABLE "User" ENABLE TRIGGER ALL;
